apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tlandgraf-poi-backend-app-dev
  annotations:
    argocd/app-name: tlandgraf-poi-backend-app-dev
    backstage.io/kubernetes-id: tlandgraf-poi-backend-app
    backstage.io/kubernetes-namespace: tlandgraf
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh23-lab/tlandgraf-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/dev-pipelines/ns/tlandgraf/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.rosa-m9x67.dusy.p1.openshiftapps.com/k8s/ns/tlandgraf/deployments/tlandgraf-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.rosa-m9x67.dusy.p1.openshiftapps.com/#https://github.com/rhdh23-lab/tlandgraf-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/tobiaslandgrafprofi"
  system: workshop-system-tlandgraf
  providesApis:
    - backend-api-tlandgraf
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-tlandgraf
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/tobiaslandgrafprofi"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-tlandgraf
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://tlandgraf-poi-backend-app-tlandgraf.apps.rosa-m9x67.dusy.p1.openshiftapps.com/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh23-lab/tlandgraf-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/tobiaslandgrafprofi"
  system: workshop-system-tlandgraf
  definition:
    $text: https://github.com/rhdh23-lab/tlandgraf-backend/tree/main/src/main/resources/META-INF/openapi.yaml
